graphql:
  servlet:
    mapping: /graphql
  playground:
    mapping: /playground
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AirbornePollutantPathfinder?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update